FROM nginx:latest

RUN atp-get update && apt install -y vim

#RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf
COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./lion_app/lion_app/django.nginx /etc/nginx/sites-available/django
RUN mkdir sites-enabled
RUN ln -s /etc/nginx/sites-available/django /etc/nginx/sites-enabled/django 

CMD [ "nginx" ]

EXPOSE 80
EXPOSE 443