version: '3' #compose 파일버전

services: #애플리케이션의 컨테이너를 정의하는 섹션
  # django app
  lion-app:
    container_name: lion-app-dc #컨테이너의 이름을 정의
    build: #Dockerfile을 사용하여 이미지를 빌드
      context: lion_app #이미지 위치지정
      dockerfile: Dockerfile
    image: lion-app #도커 이미지 이름 정의
    ports: #컨테이너가 사용할 포트와 호스트에서 사용할 포트 지정
      - "8000:8000"
    volumes:
      - ./lion_app:/app
      - "staticfiles:/var/www/html/static"
    command:
      - "/start"

  # nginx
  nginx:
    depends_on:
      - lion-app
    container_name: lion-nginx-dc
    build:
      context: .
      dockerfile: Dockerfile.nginx_ubt
    image: lion-nginx
    ports:
      - "8888:80"
    volumes:
      - "staticfiles:/var/www/html/static"

volumes:
  staticfiles: